window.AI_MIND_SCENARIOS = {
  writing: {
    accent: '#8b5a3c', code: { vi: 'NHIỆM VỤ 02', en: 'MISSION 02' },
    title: { vi: 'Viết trong ranh giới bằng chứng', en: 'Evidence-Locked Writing' },
    subtitle: { vi: 'Bản tóm lược chính sách 1.200 từ về chương trình bữa ăn học đường, dựa trên một gói bằng chứng mô phỏng.', en: 'A 1,200-word policy brief on a school-meals program, based on a simulated evidence packet.' },
    disclosure: { vi: 'Tất cả nghiên cứu, số liệu và trích dẫn trong nhiệm vụ này đều là mô phỏng để giảng dạy.', en: 'All studies, numbers, and citations in this mission are simulated for teaching.' },
    deadline: '08:30', duration: { vi: '5 phút', en: '5 min' }, course: [['01', 'control-philosophy'], ['04', 'skills'], ['06', 'applied-research'], ['12', 'instructor-notes']],
    briefing: { vi: 'Giám đốc cần bản tóm lược chính sách trước cuộc họp sáng. Gói bằng chứng gồm 6 nguồn: 2 thử nghiệm ngẫu nhiên có đối chứng, 2 nghiên cứu quan sát, 1 báo cáo triển khai và 1 bảng chi phí. Tác nhân AI có thể viết rất nhanh; rủi ro là nó sẽ lấp khoảng trống bằng những câu nghe hợp lý.', en: 'The director needs a policy brief before the morning meeting. The evidence packet has six sources: two RCTs, two observational studies, one implementation report, and one cost table. The agent can write quickly; the risk is that it fills evidence gaps with plausible prose.' },
    checkpoints: [
      { title: { vi: 'Bắt đầu từ đâu?', en: 'Where do you start?' }, situation: { vi: 'Tác nhân AI đề nghị viết luôn bản nháp hoàn chỉnh để “có cái mà sửa”.', en: 'The agent proposes drafting the full brief immediately so you have something to edit.' }, fast: { label: { vi: 'Cho viết toàn bộ bản nháp', en: 'Draft the full brief' }, detail: { vi: 'Một yêu cầu, 1.200 từ, giọng chính sách chắc chắn.', en: 'One prompt, 1,200 words, confident policy voice.' }, effect: { vi: 'Bản nháp trôi chảy nhưng 7 luận điểm chưa được nối với nguồn.', en: 'The draft reads well, but seven claims have no source mapping.' } }, control: { label: { vi: 'Lập ma trận luận điểm - bằng chứng', en: 'Build a claim-evidence matrix' }, detail: { vi: 'Nguồn nào đỡ luận điểm nào; thiết kế, mẫu và hạn chế đi cùng.', en: 'Map each claim to a source, design, sample, and limitation.' }, effect: { vi: 'Phạm vi viết được khoá vào 9 luận điểm có bằng chứng.', en: 'The writing scope is locked to nine evidence-backed claims.' } } },
      { title: { vi: 'Dàn ý có cần duyệt?', en: 'Does the outline need approval?' }, situation: { vi: 'Tác nhân AI tạo cấu trúc: vấn đề, bằng chứng, khuyến nghị, kết luận.', en: 'The agent creates a structure: problem, evidence, recommendation, conclusion.' }, fast: { label: { vi: 'Dàn ý ổn, viết tiếp', en: 'Looks fine, continue' }, detail: { vi: 'Không kiểm tra logic nối bằng chứng với khuyến nghị.', en: 'Skip checking how evidence supports the recommendation.' }, effect: { vi: 'Khuyến nghị xuất hiện trước khi các đánh đổi được trình bày.', en: 'The recommendation appears before the trade-offs are established.' } }, control: { label: { vi: 'Khoá bản đồ lập luận', en: 'Lock the argument map' }, detail: { vi: 'Mỗi mục phải trả lời một câu hỏi và có nguồn bằng chứng phụ trách.', en: 'Each section answers one question and has an evidence owner.' }, effect: { vi: 'Dàn ý có luận điểm, phản biện và hạn chế rõ ràng.', en: 'The outline now carries claims, counterpoints, and limitations.' } } },
      { title: { vi: 'Tác nhân AI dùng từ “tác động”.', en: 'The agent writes “impact”.' }, situation: { vi: 'Một nghiên cứu quan sát cho thấy tỷ lệ đi học cao hơn 6 điểm phần trăm. Tác nhân AI gọi đó là tác động của chương trình.', en: 'An observational study reports attendance six percentage points higher. The agent calls it the program impact.' }, fast: { label: { vi: 'Giữ câu mạnh', en: 'Keep the strong sentence' }, detail: { vi: 'Bản tóm lược chính sách cần dứt khoát.', en: 'A policy brief should sound decisive.' }, effect: { vi: 'Kết quả liên hệ bị trình bày thành kết luận nhân quả.', en: 'An associational result is presented as a causal claim.' } }, control: { label: { vi: 'Hạ luận điểm về đúng thiết kế', en: 'Match claim to design' }, detail: { vi: 'Đổi thành “có liên hệ với”, tách riêng bằng chứng từ thử nghiệm ngẫu nhiên.', en: 'Use “is associated with” and separate the RCT evidence.' }, effect: { vi: 'Ngôn ngữ nhân quả chỉ xuất hiện ở nơi thiết kế nghiên cứu có thể bảo vệ.', en: 'Causal language appears only where the design supports it.' } } },
      { title: { vi: 'Trích dẫn trông đã đầy đủ.', en: 'The citations look complete.' }, situation: { vi: 'Tác nhân AI cung cấp trích dẫn tác giả - năm và danh mục tài liệu hoàn chỉnh, nhưng chưa có bằng chứng đến cấp trang.', en: 'The agent provides complete author-year citations and a bibliography, but no page-level evidence.' }, fast: { label: { vi: 'Gửi bản tóm lược', en: 'Send the brief' }, detail: { vi: 'Định dạng đúng, hạn chót còn 11 phút.', en: 'Formatting is clean; eleven minutes remain.' }, effect: { vi: 'Hai trích dẫn không chứa luận điểm mà câu chữ gán cho chúng.', en: 'Two citations do not contain the claims attributed to them.' } }, control: { label: { vi: 'Truy từng luận điểm', en: 'Trace every claim' }, detail: { vi: 'Ghi nguồn, trang hoặc bảng, bằng chứng chính xác và hạn chế.', en: 'Record source, page or table, exact support, and limitation.' }, effect: { vi: 'Hai luận điểm bị xoá, ba câu được hạ mức chắc chắn.', en: 'Two claims are removed and three sentences are softened.' } } }
    ],
    result: { good: { vi: 'Bản tóm lược bám bằng chứng, phân biệt liên hệ với nhân quả, và truy được từng luận điểm quan trọng về nguồn.', en: 'The brief stays inside the evidence, separates association from causation, and traces every major claim to source.' }, bad: { vi: 'Bản tóm lược đọc rất thuyết phục nhưng câu chữ đã vượt ra ngoài gói bằng chứng.', en: 'The brief is persuasive, but the prose has outrun the evidence packet.' } },
    artifacts: [
      { title: { vi: 'Bản giao việc viết có kiểm chứng', en: 'Writing contract' }, body: { vi: '## Bản giao việc viết trong ranh giới bằng chứng\n\n**Độc giả.** Người ra quyết định có ít thời gian.\n**Ranh giới nguồn.** Chỉ dùng gói bằng chứng đã duyệt.\n**Quy tắc luận điểm.** Mỗi luận điểm quan trọng phải nối với nguồn, thiết kế, mẫu và hạn chế.\n**Quy tắc nhân quả.** Chỉ dùng ngôn ngữ nhân quả khi chiến lược nhận diện cho phép.\n**Quy trình.** Ma trận luận điểm - bằng chứng -> bản đồ lập luận -> viết từng mục -> truy trích dẫn -> biên tập cuối.\n**Hoàn thành khi.** Có bản tóm lược, bản đồ nguồn, ghi chú bằng chứng còn thiếu và kiểm toán luận điểm cuối.', en: '## Evidence-locked writing contract\n\n**Audience.** Decision-maker with limited time.\n**Source boundary.** Use only the approved evidence packet.\n**Claim rule.** Every material claim maps to a source, design, sample, and limitation.\n**Causal rule.** Use causal language only when the identification strategy supports it.\n**Workflow.** Claim-evidence matrix -> argument map -> section drafts -> citation trace -> final edit.\n**Done.** Brief, source map, unresolved-evidence note, and final claim audit.' } },
      { title: { vi: 'Ma trận luận điểm - bằng chứng', en: 'Claim-evidence matrix' }, body: { vi: '## Ma trận luận điểm - bằng chứng\n\n| Luận điểm | Nguồn | Thiết kế | Bằng chứng chính xác | Hạn chế | Cách diễn đạt được phép |\n|---|---|---|---|---|---|\n|  |  |  | trang/bảng |  | nhân quả / liên hệ / mô tả |\n\n### Kiểm tra cuối\n- [ ] Mọi con số đều truy được.\n- [ ] Không có trích dẫn trang trí.\n- [ ] Khuyến nghị được tách khỏi phát hiện.\n- [ ] Hạn chế được nêu rõ, không chôn trong chú thích.', en: '## Claim-evidence matrix\n\n| Claim | Source | Design | Exact support | Limitation | Allowed language |\n|---|---|---|---|---|---|\n|  |  |  | page/table |  | causal / associational / descriptive |\n\n### Final checks\n- [ ] Every number is traceable.\n- [ ] No citation is decorative.\n- [ ] Recommendations are separated from findings.\n- [ ] Limitations are visible, not buried.' } }
    ]
  },
  operations: {
    accent: '#476b57', code: { vi: 'NHIỆM VỤ 03', en: 'MISSION 03' }, title: { vi: 'Phòng điều hành thực địa', en: 'Fieldwork Control Room' },
    subtitle: { vi: 'Điều hành ca kiểm tra chất lượng lúc 09:00 cho một dự án khảo sát hộ gia đình mô phỏng.', en: 'Run the 09:00 QA shift for a simulated household survey project.' },
    disclosure: { vi: 'Dự án, người trả lời và các lỗi kiểm tra chất lượng trong nhiệm vụ đều là mô phỏng.', en: 'The project, respondents, and QA errors in this mission are simulated.' },
    deadline: '09:00', duration: { vi: '5 phút', en: '5 min' }, course: [['05', 'connectors-tools'], ['07', 'project-workflows'], ['08', 'automation-routines']],
    briefing: { vi: 'Có 1.842 phiếu từ 24 điều tra viên gửi về qua đêm. Bảng điều khiển báo 63 lỗi, 11 điểm GPS ngoài vùng và 4 cuộc phỏng vấn quá ngắn. Trưởng nhóm cần bản tóm tắt buổi sáng có người phụ trách, hạn xử lý và quy tắc chuyển cấp.', en: '1,842 submissions arrived overnight from 24 enumerators. The dashboard flags 63 errors, 11 out-of-area GPS points, and four interviews that are too short. The team lead needs a morning brief with owners, deadlines, and escalation.' },
    checkpoints: [
      { title: { vi: 'Tác nhân AI được đọc và gửi gì?', en: 'What may the agent read and send?' }, situation: { vi: 'Tác nhân AI xin quyền vào Gmail, Drive và toàn bộ dữ liệu xuất để tự tạo báo cáo rồi gửi nhóm.', en: 'The agent requests Gmail, Drive, and the full export so it can create and send the team report.' }, fast: { label: { vi: 'Kết nối tất cả', en: 'Connect everything' }, detail: { vi: 'Nhanh nhất, bỏ qua việc lập bản đồ dữ liệu nhạy cảm.', en: 'Fastest; skip mapping sensitive fields.' }, effect: { vi: 'Tên, số điện thoại và câu trả lời tự do đi vào ngữ cảnh xử lý.', en: 'Names, phone numbers, and respondent free text enter the prompt context.' } }, control: { label: { vi: 'Đặt ranh giới kết nối', en: 'Create connector boundaries' }, detail: { vi: 'Chỉ dùng bản trích đã ẩn danh; thư điện tử chỉ được lưu ở dạng nháp.', en: 'Use a de-identified QA extract; email remains draft-only.' }, effect: { vi: 'Tác nhân AI chỉ thấy mã giả, mã lỗi và danh sách nhân sự.', en: 'The agent sees pseudonymous IDs, error codes, and the team roster only.' } } },
      { title: { vi: '63 lỗi có nên để chung một danh sách?', en: 'Sixty-three errors: one list?' }, situation: { vi: 'Tác nhân AI chuẩn bị gửi bảng lỗi được xếp theo mã bản ghi.', en: 'The agent prepares to send an error spreadsheet sorted by record ID.' }, fast: { label: { vi: 'Gửi danh sách lỗi thô', en: 'Send the raw error list' }, detail: { vi: 'Mỗi nhóm tự tìm lỗi của mình.', en: 'Let the team find its own issues.' }, effect: { vi: 'Không có mức độ nghiêm trọng, người phụ trách hay hạn xử lý; lỗi quan trọng chìm trong danh sách.', en: 'No severity, owner, or SLA; critical issues disappear in the list.' } }, control: { label: { vi: 'Chuyển lỗi thành đầu việc', en: 'Triage into task records' }, detail: { vi: 'Gắn mức độ, người phụ trách, hạn xử lý, bằng chứng và hành động tiếp theo.', en: 'Add severity, owner, deadline, evidence, and next action.' }, effect: { vi: '63 lỗi trở thành 31 đầu việc; 6 đầu việc được đánh dấu nghiêm trọng.', en: 'Sixty-three errors become 31 tasks, six marked critical.' } } },
      { title: { vi: 'Điểm GPS ngoài vùng có nên tự động gửi cảnh báo?', en: 'Should GPS flags auto-notify?' }, situation: { vi: 'Hệ thống muốn gửi cảnh báo trực tiếp cho điều tra viên ngay khi GPS nằm ngoài vùng khảo sát.', en: 'The automation wants to alert enumerators immediately when GPS falls outside the polygon.' }, fast: { label: { vi: 'Bật gửi tự động', en: 'Enable auto-send' }, detail: { vi: 'Mọi cờ cảnh báo đều trở thành tin nhắn.', en: 'Every flag becomes a message.' }, effect: { vi: 'Bốn điểm gần ranh giới tạo cảnh báo giả do sai số GPS.', en: 'Four near-boundary points create false alerts due to GPS error.' } }, control: { label: { vi: 'Thêm cổng duyệt', en: 'Add a review gate' }, detail: { vi: 'Dùng vùng đệm 200 m, kiểm tra thời gian và yêu cầu giám sát viên phê duyệt.', en: 'Use a 200m buffer, check timestamps, and require supervisor approval.' }, effect: { vi: '11 cảnh báo còn 5 trường hợp thực sự cần theo dõi.', en: 'Eleven flags become five cases that require real follow-up.' } } },
      { title: { vi: 'Khi nào tự động hóa phải dừng?', en: 'When must automation stop?' }, situation: { vi: 'Hai điều tra viên có tỷ lệ phỏng vấn quá ngắn tăng mạnh. Tác nhân AI có thể tự giao nhiệm vụ đào tạo lại.', en: 'Two enumerators show a sharp rise in short interviews. The agent can automatically assign retraining.' }, fast: { label: { vi: 'Cho tác nhân AI xử lý', en: 'Let the agent handle it' }, detail: { vi: 'Tạo đầu việc và gửi cảnh báo kỷ luật.', en: 'Create tasks and send disciplinary warnings.' }, effect: { vi: 'Một thiết bị bị lỗi bộ đếm thời gian nhưng điều tra viên bị quy trách nhiệm.', en: 'A device timer failure is misclassified as enumerator misconduct.' } }, control: { label: { vi: 'Chuyển cho con người', en: 'Escalate to a human' }, detail: { vi: 'Dừng tự động hóa; giám sát viên xem âm thanh, nhật ký thiết bị và lịch sử.', en: 'Stop automation; supervisor reviews audio, device logs, and history.' }, effect: { vi: 'Một lỗi thiết bị và một trường hợp cần hướng dẫn thêm được tách đúng.', en: 'A device fault and one coaching case are correctly separated.' } } }
    ],
    result: { good: { vi: 'Bản tóm tắt buổi sáng chỉ dùng dữ liệu cần thiết, mỗi đầu việc có người phụ trách rõ ràng và tự động hóa dừng đúng lúc cần phán đoán.', en: 'The morning brief uses minimal data, assigns clear owners, and stops automation when judgment is required.' }, bad: { vi: 'Quy trình nhanh nhưng gửi quá nhiều dữ liệu, tạo cảnh báo giả và biến nghi vấn thành quyết định nhân sự.', en: 'The workflow is fast, but overshares data, creates false alerts, and turns suspicion into a personnel decision.' } },
    artifacts: [
      { title: { vi: 'Quy trình vận hành lúc 09:00', en: '9AM operations runbook' }, body: { vi: '## Quy trình vận hành dự án lúc 09:00\n\n1. Lấy bản trích kiểm tra chất lượng đã ẩn danh.\n2. Kiểm tra số dòng và thời điểm cập nhật.\n3. Gom lỗi theo quy tắc, mức độ, người phụ trách và hạn xử lý.\n4. Kiểm tra dương tính giả trước khi liên hệ.\n5. Soạn bản tóm tắt buổi sáng; con người duyệt trước khi gửi.\n6. Chuyển cấp các vấn đề về riêng tư, an toàn, nhân sự hoặc lỗi hệ thống chưa giải thích được.\n7. Ghi lại quyết định và khép vòng xử lý trước 17:00.', en: '## 09:00 project operations runbook\n\n1. Pull de-identified QA extract.\n2. Validate row count and refresh timestamp.\n3. Group errors by rule, severity, owner, and deadline.\n4. Apply false-positive checks before outreach.\n5. Draft morning brief; human approves distribution.\n6. Escalate privacy, safeguarding, personnel, or unexplained systemic issues.\n7. Log decisions and close the loop by 17:00.' } },
      { title: { vi: 'Ma trận chuyển cấp', en: 'Escalation matrix' }, body: { vi: '## Ma trận chuyển cấp\n\n| Tín hiệu | Hành động tự động | Người phụ trách | Quy tắc dừng |\n|---|---|---|---|\n| Lỗi kiểm tra thông thường | Tạo đầu việc | Quản lý dữ liệu | Không |\n| GPS ngoài vùng đệm | Chuẩn bị bằng chứng | Giám sát thực địa | Liên hệ cần phê duyệt |\n| Có thể gây rủi ro cho người trả lời | Đóng băng trường hợp | Phụ trách an toàn | Không gửi tin tự động |\n| Có thể là vi phạm của nhân sự | Chỉ thu thập bằng chứng | Trưởng dự án | Không phán quyết tự động |', en: '## Escalation matrix\n\n| Trigger | Automation action | Human owner | Stop rule |\n|---|---|---|---|\n| Routine validation error | Create task | Data manager | None |\n| GPS outside buffered area | Prepare evidence | Field supervisor | Contact requires approval |\n| Possible respondent risk | Freeze case | Safeguarding lead | No automated message |\n| Possible staff misconduct | Collect evidence only | Project lead | No automated judgment |' } }
    ]
  },
  'large-data': {
    accent: '#4c6381', code: { vi: 'NHIỆM VỤ 04', en: 'MISSION 04' }, title: { vi: 'Năm mươi triệu dòng', en: 'Fifty Million Rows' },
    subtitle: { vi: 'Xây bảng doanh nghiệp - năm từ 50 triệu giao dịch mà không làm cạn bộ nhớ hoặc mất khả năng tái lập.', en: 'Build a firm-year table from 50 million transactions without exhausting memory or losing reproducibility.' },
    disclosure: { vi: 'Tệp, cấu trúc dữ liệu, phép đo chuẩn và số liệu trong nhiệm vụ đều là mô phỏng.', en: 'The files, schema, benchmarks, and numbers in this mission are simulated.' },
    deadline: '17:00', duration: { vi: '5 phút', en: '5 min' }, course: [['02', 'setup-orientation'], ['06', 'applied-research'], ['08', 'automation-routines'], ['09', 'crawling-data']],
    briefing: { vi: '`transactions_2021_2025.csv` nặng 38 GB, khoảng 50 triệu dòng. Mục tiêu là bảng doanh nghiệp - năm gồm doanh thu, số giao dịch và thị trường chính. Máy có 16 GB bộ nhớ; cấu trúc dữ liệu thay đổi từ năm 2023.', en: '`transactions_2021_2025.csv` is 38GB, roughly 50 million rows. The target is a firm-year table with revenue, transaction count, and primary market. The machine has 16GB RAM, and the schema changes in 2023.' },
    checkpoints: [
      { title: { vi: 'Đọc tệp thế nào?', en: 'How do you read the file?' }, situation: { vi: 'Tác nhân AI đề nghị dùng `pandas.read_csv()` rồi xử lý như một bảng dữ liệu thông thường.', en: 'The agent proposes `pandas.read_csv()` and ordinary dataframe processing.' }, fast: { label: { vi: 'Cứ chạy thử', en: 'Try it' }, detail: { vi: 'Nếu lỗi thì tối ưu sau.', en: 'Optimize only if it fails.' }, effect: { vi: 'Tiến trình dùng hết bộ nhớ, ghi tráo 41 GB rồi bị hệ thống dừng sau 27 phút.', en: 'The process exhausts RAM, swaps 41GB, and is killed after 27 minutes.' } }, control: { label: { vi: 'Khảo sát rồi chia lô', en: 'Profile, then chunk' }, detail: { vi: 'Đọc tiêu đề và mẫu, chọn kiểu dữ liệu, cột cần dùng và kích thước lô.', en: 'Read header and samples, then choose dtypes, columns, and chunk size.' }, effect: { vi: 'Mức dùng bộ nhớ cao nhất còn 2,8 GB; quy trình có phép đo tốc độ xử lý.', en: 'Peak memory falls to 2.8GB and the pipeline gets a throughput benchmark.' } } },
      { title: { vi: 'Cấu trúc dữ liệu thay đổi giữa các năm.', en: 'The schema changes across years.' }, situation: { vi: 'Năm 2023 đổi `firm_id` thành `seller_id`; mã tiền tệ bắt đầu có chữ thường.', en: 'In 2023, `firm_id` becomes `seller_id`, and currency codes begin appearing in lowercase.' }, fast: { label: { vi: 'Đổi tên khi gặp lỗi', en: 'Rename when errors appear' }, detail: { vi: 'Vá trực tiếp trong vòng xử lý.', en: 'Patch directly inside the processing loop.' }, effect: { vi: 'Năm 2023 chạy được nhưng năm 2024 âm thầm làm rỗng 8% mã doanh nghiệp.', en: '2023 runs, but 2024 silently nulls eight percent of firm IDs.' } }, control: { label: { vi: 'Viết hợp đồng cấu trúc dữ liệu', en: 'Write a schema contract' }, detail: { vi: 'Khai báo bản ánh xạ theo phiên bản, trường bắt buộc, kiểu dữ liệu và giá trị cho phép.', en: 'Define version maps, required fields, types, and allowed values.' }, effect: { vi: 'Quy trình dừng ngay khi gặp cấu trúc lạ và ghi lại từng phép ánh xạ.', en: 'The pipeline fails fast on unknown schemas and logs every mapping.' } } },
      { title: { vi: 'Có cần điểm lưu?', en: 'Do you need checkpoints?' }, situation: { vi: 'Toàn bộ công việc ước tính chạy 3 giờ. Tác nhân AI có thể chỉ ghi kết quả cuối một lần.', en: 'The full job is estimated to take three hours. The agent can write the final output once.' }, fast: { label: { vi: 'Chạy một mạch', en: 'Run end to end' }, detail: { vi: 'Ít tệp trung gian, mã ngắn hơn.', en: 'Fewer intermediate files and shorter code.' }, effect: { vi: 'Lỗi ở lô 87 buộc chạy lại từ đầu; nguồn gốc xử lý bị mất.', en: 'A failure at chunk 87 forces a full restart and loses provenance.' } }, control: { label: { vi: 'Lưu theo phân vùng', en: 'Checkpoint by partition' }, detail: { vi: 'Dùng tệp kê khai, mã kiểm tra, số dòng và trạng thái có thể tiếp tục.', en: 'Use a manifest, checksums, row counts, and resumable state.' }, effect: { vi: 'Công việc tiếp tục từ phân vùng 87 và giữ nguyên dấu vết kiểm toán.', en: 'The job resumes from partition 87 with an audit trail intact.' } } },
      { title: { vi: 'Kết quả trông hợp lý.', en: 'The output looks plausible.' }, situation: { vi: 'Bảng doanh nghiệp - năm có 2,1 triệu dòng. Tổng doanh thu tăng đều và không có lỗi hiển thị.', en: 'The firm-year table has 2.1 million rows. Total revenue rises smoothly and no exception appears.' }, fast: { label: { vi: 'Xuất bảng và gửi', en: 'Export and send' }, detail: { vi: 'Kiểm tra tính hợp lý như vậy là đủ.', en: 'The plausibility check is enough.' }, effect: { vi: 'Mã giao dịch trùng làm doanh thu năm 2024 cao hơn 11%.', en: 'Duplicate transaction IDs inflate 2024 revenue by eleven percent.' } }, control: { label: { vi: 'Chạy bộ kiểm chứng', en: 'Run the validation suite' }, detail: { vi: 'Kiểm tra tính duy nhất, đối soát, mẫu phân tầng và trường hợp biên.', en: 'Check uniqueness, reconciliation, stratified samples, and edge cases.' }, effect: { vi: 'Phát hiện một lô trùng; tổng hợp khớp nguồn sau khi sửa.', en: 'A duplicate batch is found; aggregates reconcile after the fix.' } } }
    ],
    result: { good: { vi: 'Quy trình chạy trong giới hạn tài nguyên, tiếp tục được sau lỗi, dừng ngay khi cấu trúc thay đổi và đối soát được với nguồn.', en: 'The pipeline stays within resource limits, resumes safely, fails fast on schema drift, and reconciles with the source.' }, bad: { vi: 'Kết quả có vẻ hoàn thành nhưng chứa giá trị rỗng âm thầm, phải chạy lại toàn bộ và tổng hợp sai 11%.', en: 'The output appears complete, but carries silent nulls, full restarts, and an aggregate that is wrong by eleven percent.' } },
    artifacts: [
      { title: { vi: 'Bản giao việc xử lý dữ liệu lớn', en: 'Large-data execution contract' }, body: { vi: '## Bản giao việc xử lý dữ liệu lớn\n\n**Đầu vào.** Tệp nguồn bất biến và bản ánh xạ phiên bản cấu trúc.\n**Ngân sách tài nguyên.** Ghi trước mức dùng bộ nhớ cao nhất, dung lượng đĩa và tốc độ dự kiến.\n**Phương pháp.** Chỉ đọc cột cần dùng, khai báo kiểu dữ liệu và xử lý theo phân vùng hoặc lô.\n**Điểm lưu.** Tệp kê khai ghi phân vùng, mã kiểm tra, số dòng vào/ra, trạng thái và phiên bản mã.\n**Quy tắc lỗi.** Cấu trúc lạ hoặc đối soát thất bại sẽ dừng quy trình.\n**Hoàn thành khi.** Có bảng tổng hợp tái lập được, tệp kê khai, báo cáo kiểm chứng và hướng dẫn chạy lại.', en: '## Large-data execution contract\n\n**Input.** Immutable source files plus schema version map.\n**Resource budget.** Peak memory, disk allowance, and expected throughput recorded before full run.\n**Method.** Column projection + explicit dtypes + partitioned/chunked processing.\n**Checkpoint.** Manifest records partition, checksum, rows in/out, status, and code version.\n**Failure rule.** Unknown schema or failed reconciliation stops the pipeline.\n**Done.** Reproducible aggregate, manifest, validation report, and rerun instructions.' } },
      { title: { vi: 'Danh sách kiểm tra dữ liệu lớn', en: 'Large-data QA checklist' }, body: { vi: '## Danh sách kiểm tra dữ liệu lớn\n\n- [ ] Khảo sát nhiều năm trước khi chọn kiểu dữ liệu.\n- [ ] Kiểm tra cột bắt buộc và giá trị cho phép theo từng phiên bản cấu trúc.\n- [ ] Ghi số dòng trước và sau mỗi bộ lọc.\n- [ ] Bắt buộc khoá duy nhất hoặc giải thích bản ghi trùng có chủ đích.\n- [ ] Đối soát tổng với các phân vùng nguồn.\n- [ ] Kiểm tra mẫu phân tầng và trường hợp biên.\n- [ ] Thử tiếp tục từ một phân vùng bị lỗi.\n- [ ] Lưu tệp kê khai, mã kiểm tra, nhật ký và phiên bản mã.', en: '## Large-data QA checklist\n\n- [ ] Profile multiple years before selecting dtypes.\n- [ ] Validate required columns and allowed values per schema version.\n- [ ] Record row counts before and after every filter.\n- [ ] Enforce key uniqueness or document intended duplicates.\n- [ ] Reconcile totals to source partitions.\n- [ ] Inspect stratified samples and edge cases.\n- [ ] Test resume from a failed partition.\n- [ ] Save manifest, checksums, logs, and code version.' } }
    ]
  }
};
