(function(){
  var TEXT={
    vi:{simulator:'Mô phỏng',theme:'Giao diện',briefing:'TÓM TẮT NHIỆM VỤ',start:'Bắt đầu nhiệm vụ →',back:'← Tất cả mô phỏng',fast:'NHANH · BUÔNG',control:'CHẬM · CẦM LÁI',consequence:'HỆ QUẢ',continue:'Quyết định tiếp theo →',record:'HỒ SƠ NHIỆM VỤ',controlPoints:'ĐIỂM KIỂM SOÁT',riskCount:'RỦI RO ĐÃ CHẤP NHẬN',courseParts:'PHẦN HỌC LIÊN QUAN',ledger:'Sổ rủi ro',takeHome:'Sản phẩm mang về',takeHomeSub:'Sao chép và dùng trong dự án thật.',replay:'↺ Chơi lại',otherMissions:'Xem nhiệm vụ khác →',good:'KIỂM SOÁT ĐƯỢC',mixed:'CÓ LỖ HỔNG',bad:'MẤT KIỂM SOÁT',copied:'Đã sao chép sản phẩm'},
    en:{simulator:'Simulator',theme:'Theme',briefing:'MISSION BRIEF',start:'Start mission →',back:'← All simulators',fast:'FAST · HANDS OFF',control:'SLOW · TAKE CONTROL',consequence:'CONSEQUENCE',continue:'Next decision →',record:'MISSION RECORD',controlPoints:'CONTROL POINTS',riskCount:'RISKS ACCEPTED',courseParts:'COURSE PARTS',ledger:'Risk ledger',takeHome:'Take-home artifacts',takeHomeSub:'Copy and use them in real projects.',replay:'↺ Replay',otherMissions:'Explore another mission →',good:'UNDER CONTROL',mixed:'CONTROL GAPS',bad:'CONTROL LOST',copied:'Artifact copied'}
  };
  var params=new URLSearchParams(location.search),id=params.get('mission')||'writing',scenario=window.AI_MIND_SCENARIOS[id]||window.AI_MIND_SCENARIOS.writing;
  var lang=localStorage.getItem('aiMindLang')||'vi',theme=localStorage.getItem('theme')||'',index=0,answers=[];
  if(theme==='dark'||(!theme&&matchMedia('(prefers-color-scheme: dark)').matches))document.documentElement.dataset.theme='dark';
  document.documentElement.style.setProperty('--accent',scenario.accent);
  function L(v){return typeof v==='string'?v:v[lang]}
  var SCREEN_FOCUS_TARGET={'brief-screen':'mission-title','play-screen':'decision-title','effect-screen':'effect-title','result-screen':'result-screen'};
  function show(id){document.querySelectorAll('.screen').forEach(function(x){x.classList.toggle('on',x.id===id)});var focusEl=document.getElementById(SCREEN_FOCUS_TARGET[id]);if(focusEl)focusEl.focus()}
  function applyText(){document.documentElement.lang=lang;document.title=L(scenario.title)+' — '+(lang==='vi'?'Mô phỏng':'Simulator');document.querySelectorAll('[data-t]').forEach(function(el){el.textContent=TEXT[lang][el.dataset.t]});document.getElementById('lang-btn').textContent=lang==='vi'?'EN':'VN';renderBrief();if(document.getElementById('play-screen').classList.contains('on'))renderDecision();if(document.getElementById('result-screen').classList.contains('on'))renderResult()}
  function renderBrief(){document.getElementById('mission-code').textContent=L(scenario.code);document.getElementById('mission-duration').textContent=L(scenario.duration);document.getElementById('mission-title').textContent=L(scenario.title);document.getElementById('mission-subtitle').textContent=L(scenario.subtitle);document.getElementById('mission-deadline').textContent=(lang==='vi'?'HẠN CHÓT ':'DEADLINE ')+scenario.deadline;document.getElementById('mission-briefing').textContent=L(scenario.briefing);document.getElementById('mission-disclosure').textContent=L(scenario.disclosure);document.getElementById('course-links').innerHTML=scenario.course.map(function(c){return '<a href="/other/ai-mind/hub.html#course">'+(lang==='vi'?'Phần ':'Part ')+c[0]+'</a>'}).join('')}
  function renderProgress(){document.getElementById('progress').innerHTML=scenario.checkpoints.map(function(_,i){return '<i class="'+(i<index?'done':i===index?'current':'')+'"></i>'}).join('');document.getElementById('hud-score').textContent=answers.filter(function(a){return a==='control'}).length+'/'+scenario.checkpoints.length}
  function renderDecision(){var d=scenario.checkpoints[index];document.getElementById('hud-code').textContent=L(scenario.code);document.getElementById('decision-step').textContent=(lang==='vi'?'ĐIỂM KIỂM SOÁT ':'CONTROL ')+(index+1)+'/'+scenario.checkpoints.length;document.getElementById('decision-title').textContent=L(d.title);document.getElementById('decision-situation').textContent=L(d.situation);document.getElementById('fast-label').textContent=L(d.fast.label);document.getElementById('fast-detail').textContent=L(d.fast.detail);document.getElementById('control-label').textContent=L(d.control.label);document.getElementById('control-detail').textContent=L(d.control.detail);renderProgress()}
  function choose(kind){answers[index]=kind;var d=scenario.checkpoints[index],effect=d[kind];var card=document.querySelector('.effect-card');card.className='effect-card '+(kind==='control'?'good':'bad');document.getElementById('effect-mark').textContent=kind==='control'?'✓':'!';document.getElementById('effect-title').textContent=L(effect.label);document.getElementById('effect-text').textContent=L(effect.effect);document.getElementById('continue-btn').textContent=index===scenario.checkpoints.length-1?(lang==='vi'?'Xem hồ sơ nhiệm vụ →':'View mission record →'):TEXT[lang].continue;show('effect-screen')}
  function renderResult(){var score=answers.filter(function(a){return a==='control'}).length,risks=answers.length-score,key=score===answers.length?'good':score>=Math.ceil(answers.length/2)?'mixed':'bad';document.getElementById('result-stamp').textContent=TEXT[lang][key];document.getElementById('result-summary').textContent=L(key==='good'?scenario.result.good:scenario.result.bad);document.getElementById('result-score').textContent=score+'/'+answers.length;document.getElementById('result-risks').textContent=risks;document.getElementById('result-parts').textContent=scenario.course.length;document.getElementById('ledger-list').innerHTML=scenario.checkpoints.map(function(d,i){var ok=answers[i]==='control',effect=d[answers[i]];return '<div class="ledger-row '+(ok?'good':'bad')+'"><span class="ledger-mark">'+(ok?'✓':'!')+'</span><div><h3>'+L(d.title)+'</h3><p>'+L(effect.effect)+'</p></div></div>'}).join('');document.getElementById('artifact-grid').innerHTML=scenario.artifacts.map(function(a,i){return '<article class="artifact"><h3>'+L(a.title)+'</h3><pre>'+escapeHtml(L(a.body))+'</pre><button type="button" data-copy="'+i+'">'+(lang==='vi'?'Sao chép .md':'Copy .md')+'</button></article>'}).join('')}
  function escapeHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
  function toast(s){var t=document.getElementById('toast');t.textContent=s;t.classList.add('on');setTimeout(function(){t.classList.remove('on')},1800)}
  document.getElementById('start-btn').addEventListener('click',function(){index=0;answers=[];renderDecision();show('play-screen')});
  document.querySelector('.choices').addEventListener('click',function(e){var b=e.target.closest('[data-choice]');if(b)choose(b.dataset.choice)});
  document.getElementById('continue-btn').addEventListener('click',function(){if(index<scenario.checkpoints.length-1){index++;renderDecision();show('play-screen')}else{renderResult();show('result-screen')}});
  document.getElementById('replay-btn').addEventListener('click',function(){index=0;answers=[];renderBrief();show('brief-screen')});
  document.getElementById('artifact-grid').addEventListener('click',function(e){var b=e.target.closest('[data-copy]');if(!b)return;var text=L(scenario.artifacts[Number(b.dataset.copy)].body);(navigator.clipboard?navigator.clipboard.writeText(text):Promise.reject()).then(function(){toast(TEXT[lang].copied)}).catch(function(){toast(TEXT[lang].copied)})});
  document.getElementById('lang-btn').addEventListener('click',function(){lang=lang==='vi'?'en':'vi';localStorage.setItem('aiMindLang',lang);applyText()});
  document.getElementById('theme-btn').addEventListener('click',function(){var dark=document.documentElement.dataset.theme==='dark';if(dark)delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme='dark';localStorage.setItem('theme',dark?'light':'dark')});
  applyText();
})();
